# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-1.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-1.app/Contents/bin/cmake" -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-1.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/boussau/travail/DuplicationReconciliation/SVN/depotsvn/MOGESVN/moge/trunk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/boussau/travail/DuplicationReconciliation/SVN/depotsvn/MOGESVN/moge/trunk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-1.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	"/Applications/CMake 2.8-1.app/Contents/bin/cpack" --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	"/Applications/CMake 2.8-1.app/Contents/bin/cpack" --config ./CPackSourceConfig.cmake /Users/boussau/travail/DuplicationReconciliation/SVN/depotsvn/MOGESVN/moge/trunk/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-1.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/boussau/travail/DuplicationReconciliation/SVN/depotsvn/MOGESVN/moge/trunk/CMakeFiles /Users/boussau/travail/DuplicationReconciliation/SVN/depotsvn/MOGESVN/moge/trunk/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/boussau/travail/DuplicationReconciliation/SVN/depotsvn/MOGESVN/moge/trunk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RECDUP_LIB

# Build rule for target.
RECDUP_LIB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RECDUP_LIB
.PHONY : RECDUP_LIB

# fast build rule for target.
RECDUP_LIB/fast:
	$(MAKE) -f CMakeFiles/RECDUP_LIB.dir/build.make CMakeFiles/RECDUP_LIB.dir/build
.PHONY : RECDUP_LIB/fast

#=============================================================================
# Target rules for targets named ReconcileDuplications

# Build rule for target.
ReconcileDuplications: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReconcileDuplications
.PHONY : ReconcileDuplications

# fast build rule for target.
ReconcileDuplications/fast:
	$(MAKE) -f CMakeFiles/ReconcileDuplications.dir/build.make CMakeFiles/ReconcileDuplications.dir/build
.PHONY : ReconcileDuplications/fast

#=============================================================================
# Target rules for targets named deb

# Build rule for target.
deb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deb
.PHONY : deb

# fast build rule for target.
deb/fast:
	$(MAKE) -f CMakeFiles/deb.dir/build.make CMakeFiles/deb.dir/build
.PHONY : deb/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) -f CMakeFiles/dist.dir/build.make CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named rpm

# Build rule for target.
rpm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpm
.PHONY : rpm

# fast build rule for target.
rpm/fast:
	$(MAKE) -f CMakeFiles/rpm.dir/build.make CMakeFiles/rpm.dir/build
.PHONY : rpm/fast

ReconcileDuplications.o: ReconcileDuplications.cpp.o
.PHONY : ReconcileDuplications.o

# target to build an object file
ReconcileDuplications.cpp.o:
	$(MAKE) -f CMakeFiles/ReconcileDuplications.dir/build.make CMakeFiles/ReconcileDuplications.dir/ReconcileDuplications.cpp.o
.PHONY : ReconcileDuplications.cpp.o

ReconcileDuplications.i: ReconcileDuplications.cpp.i
.PHONY : ReconcileDuplications.i

# target to preprocess a source file
ReconcileDuplications.cpp.i:
	$(MAKE) -f CMakeFiles/ReconcileDuplications.dir/build.make CMakeFiles/ReconcileDuplications.dir/ReconcileDuplications.cpp.i
.PHONY : ReconcileDuplications.cpp.i

ReconcileDuplications.s: ReconcileDuplications.cpp.s
.PHONY : ReconcileDuplications.s

# target to generate assembly for a file
ReconcileDuplications.cpp.s:
	$(MAKE) -f CMakeFiles/ReconcileDuplications.dir/build.make CMakeFiles/ReconcileDuplications.dir/ReconcileDuplications.cpp.s
.PHONY : ReconcileDuplications.cpp.s

ReconciliationTools.o: ReconciliationTools.cpp.o
.PHONY : ReconciliationTools.o

# target to build an object file
ReconciliationTools.cpp.o:
	$(MAKE) -f CMakeFiles/RECDUP_LIB.dir/build.make CMakeFiles/RECDUP_LIB.dir/ReconciliationTools.cpp.o
.PHONY : ReconciliationTools.cpp.o

ReconciliationTools.i: ReconciliationTools.cpp.i
.PHONY : ReconciliationTools.i

# target to preprocess a source file
ReconciliationTools.cpp.i:
	$(MAKE) -f CMakeFiles/RECDUP_LIB.dir/build.make CMakeFiles/RECDUP_LIB.dir/ReconciliationTools.cpp.i
.PHONY : ReconciliationTools.cpp.i

ReconciliationTools.s: ReconciliationTools.cpp.s
.PHONY : ReconciliationTools.s

# target to generate assembly for a file
ReconciliationTools.cpp.s:
	$(MAKE) -f CMakeFiles/RECDUP_LIB.dir/build.make CMakeFiles/RECDUP_LIB.dir/ReconciliationTools.cpp.s
.PHONY : ReconciliationTools.cpp.s

ReconciliationTreeLikelihood.o: ReconciliationTreeLikelihood.cpp.o
.PHONY : ReconciliationTreeLikelihood.o

# target to build an object file
ReconciliationTreeLikelihood.cpp.o:
	$(MAKE) -f CMakeFiles/RECDUP_LIB.dir/build.make CMakeFiles/RECDUP_LIB.dir/ReconciliationTreeLikelihood.cpp.o
.PHONY : ReconciliationTreeLikelihood.cpp.o

ReconciliationTreeLikelihood.i: ReconciliationTreeLikelihood.cpp.i
.PHONY : ReconciliationTreeLikelihood.i

# target to preprocess a source file
ReconciliationTreeLikelihood.cpp.i:
	$(MAKE) -f CMakeFiles/RECDUP_LIB.dir/build.make CMakeFiles/RECDUP_LIB.dir/ReconciliationTreeLikelihood.cpp.i
.PHONY : ReconciliationTreeLikelihood.cpp.i

ReconciliationTreeLikelihood.s: ReconciliationTreeLikelihood.cpp.s
.PHONY : ReconciliationTreeLikelihood.s

# target to generate assembly for a file
ReconciliationTreeLikelihood.cpp.s:
	$(MAKE) -f CMakeFiles/RECDUP_LIB.dir/build.make CMakeFiles/RECDUP_LIB.dir/ReconciliationTreeLikelihood.cpp.s
.PHONY : ReconciliationTreeLikelihood.cpp.s

SpeciesTreeExploration.o: SpeciesTreeExploration.cpp.o
.PHONY : SpeciesTreeExploration.o

# target to build an object file
SpeciesTreeExploration.cpp.o:
	$(MAKE) -f CMakeFiles/RECDUP_LIB.dir/build.make CMakeFiles/RECDUP_LIB.dir/SpeciesTreeExploration.cpp.o
.PHONY : SpeciesTreeExploration.cpp.o

SpeciesTreeExploration.i: SpeciesTreeExploration.cpp.i
.PHONY : SpeciesTreeExploration.i

# target to preprocess a source file
SpeciesTreeExploration.cpp.i:
	$(MAKE) -f CMakeFiles/RECDUP_LIB.dir/build.make CMakeFiles/RECDUP_LIB.dir/SpeciesTreeExploration.cpp.i
.PHONY : SpeciesTreeExploration.cpp.i

SpeciesTreeExploration.s: SpeciesTreeExploration.cpp.s
.PHONY : SpeciesTreeExploration.s

# target to generate assembly for a file
SpeciesTreeExploration.cpp.s:
	$(MAKE) -f CMakeFiles/RECDUP_LIB.dir/build.make CMakeFiles/RECDUP_LIB.dir/SpeciesTreeExploration.cpp.s
.PHONY : SpeciesTreeExploration.cpp.s

SpeciesTreeLikelihood.o: SpeciesTreeLikelihood.cpp.o
.PHONY : SpeciesTreeLikelihood.o

# target to build an object file
SpeciesTreeLikelihood.cpp.o:
	$(MAKE) -f CMakeFiles/RECDUP_LIB.dir/build.make CMakeFiles/RECDUP_LIB.dir/SpeciesTreeLikelihood.cpp.o
.PHONY : SpeciesTreeLikelihood.cpp.o

SpeciesTreeLikelihood.i: SpeciesTreeLikelihood.cpp.i
.PHONY : SpeciesTreeLikelihood.i

# target to preprocess a source file
SpeciesTreeLikelihood.cpp.i:
	$(MAKE) -f CMakeFiles/RECDUP_LIB.dir/build.make CMakeFiles/RECDUP_LIB.dir/SpeciesTreeLikelihood.cpp.i
.PHONY : SpeciesTreeLikelihood.cpp.i

SpeciesTreeLikelihood.s: SpeciesTreeLikelihood.cpp.s
.PHONY : SpeciesTreeLikelihood.s

# target to generate assembly for a file
SpeciesTreeLikelihood.cpp.s:
	$(MAKE) -f CMakeFiles/RECDUP_LIB.dir/build.make CMakeFiles/RECDUP_LIB.dir/SpeciesTreeLikelihood.cpp.s
.PHONY : SpeciesTreeLikelihood.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... RECDUP_LIB"
	@echo "... ReconcileDuplications"
	@echo "... deb"
	@echo "... dist"
	@echo "... edit_cache"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... rpm"
	@echo "... ReconcileDuplications.o"
	@echo "... ReconcileDuplications.i"
	@echo "... ReconcileDuplications.s"
	@echo "... ReconciliationTools.o"
	@echo "... ReconciliationTools.i"
	@echo "... ReconciliationTools.s"
	@echo "... ReconciliationTreeLikelihood.o"
	@echo "... ReconciliationTreeLikelihood.i"
	@echo "... ReconciliationTreeLikelihood.s"
	@echo "... SpeciesTreeExploration.o"
	@echo "... SpeciesTreeExploration.i"
	@echo "... SpeciesTreeExploration.s"
	@echo "... SpeciesTreeLikelihood.o"
	@echo "... SpeciesTreeLikelihood.i"
	@echo "... SpeciesTreeLikelihood.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

